# Generated by Django 3.1.2 on 2020-11-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg_name', models.CharField(max_length=128, unique=True, verbose_name='分类名')),
                ('ctg_code', models.CharField(max_length=128, verbose_name='分类编号')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
                'unique_together': {('ctg_name', 'ctg_code')},
            },
        ),
        migrations.CreateModel(
            name='SpecialistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spe_dep', models.CharField(default='空', max_length=128, verbose_name='单位及部门')),
                ('spe_name', models.CharField(max_length=128, verbose_name='姓名')),
                ('spe_gender', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=128, verbose_name='性别')),
                ('spe_birth', models.DateField(verbose_name='出生年月')),
                ('spe_company', models.CharField(default='空', max_length=128, verbose_name='工作单位')),
                ('spe_tel', models.CharField(default='空', max_length=128, verbose_name='联系电话')),
                ('spe_title', models.CharField(default='空', max_length=128, verbose_name='职称')),
                ('spe_job', models.CharField(default='空', max_length=128, verbose_name='职务')),
                ('spe_station', models.CharField(choices=[('专业技术', '专业技术'), ('管理', '管理'), ('工勤', '工勤'), ('双肩挑', '双肩挑')], default='专业技术', max_length=128, verbose_name='受聘岗位')),
                ('spe_edu', models.CharField(default='空', max_length=128, verbose_name='学历')),
                ('spe_code', models.IntegerField(default=0, verbose_name='随机序号')),
                ('spe_info', models.TextField(blank=True, verbose_name='备注')),
                ('spe_ctg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spe_ctg1', to='specialistApp.category', verbose_name='所从事专业一')),
                ('spe_ctg2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spe_ctg2', to='specialistApp.category', verbose_name='所从事专业二')),
                ('spe_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spe_major', to='specialistApp.category', verbose_name='所学专业')),
            ],
            options={
                'verbose_name': '考官信息',
                'verbose_name_plural': '考官信息',
            },
        ),
    ]
