# Generated by Django 3.1.2 on 2020-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistmodel',
            name='spe_dep',
        ),
        migrations.AddField(
            model_name='specialistmodel',
            name='spe_cid',
            field=models.CharField(blank=True, max_length=128, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='specialistmodel',
            name='spe_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月'),
        ),
    ]
