# Generated by Django 3.1.2 on 2020-11-17 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0002_auto_20201116_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistmodel',
            name='spe_cid',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MaxLengthValidator(18), django.core.validators.MinLengthValidator(18)], verbose_name='身份证号'),
        ),
    ]
