# Generated by Django 3.1.2 on 2020-11-19 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0003_auto_20201117_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistmodel',
            name='spe_age',
            field=models.CharField(blank=True, default='0', max_length=128, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='specialistmodel',
            name='spe_cid',
            field=models.CharField(blank=True, default='0', max_length=128, validators=[django.core.validators.MaxLengthValidator(18), django.core.validators.MinLengthValidator(18)], verbose_name='身份证号'),
        ),
    ]
