# Generated by Django 3.1.2 on 2020-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0004_auto_20201119_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistmodel',
            name='spe_age',
            field=models.IntegerField(blank=True, default='0', max_length=128, verbose_name='年龄'),
        ),
    ]
